sudo: false

language: node_js
node_js:
- '4'

env:
  global:
    - secure: BkvUeOklB3My+07VZaGSOLQbRWrsPMf6G5oaZPA/MtNQC7Iaf0nKm4rWUSjIyHCFLNV5fzWTLAZU+bEhqcjD1swc+x6uCOP1O62oYyTiTxxgTB8S8tWsRbCzD05knvbvlMmeKYV1IxpT/w15mjvtnycgA1qOHthcukTLWfZKZeUO0o+AGRz2HVSlM+mFpRg7xus0o4hNT50uH1cKx25AAYEBhnuuV8fQ71Ru2ppwAGbowPvwoohjHOFF2IR/RXGj7NZxym3GjwxD/VsxEd+Hez/rfXR8OrZktvIZyc4kqW0UsDagOTqxw5a6rQc5OyFz1JW0I9iu9npH01t+cShoTafgkz3MYMWy1UATIaPZk7JgjblFWoZAZpDAQVI/GRK8U4bhRaZLW/DmJUFLhD8Tkh0OK6LbtZHiMWL6AwZ9a/tjLhrDLPT8qyUryz/qt828C5uNKE+ZAl6TyHdjs2jZGkG/VqETWW/m0atJJaZOzzESwJsqVxayBMuY6+9HFcP1Fk4D1fMuNRfjDQpMN+jlVWQsak4+D3T/CZAmSeAo8BoMTi2JFbiYc8PSDltb5u30+LdneoBSEGckNZNvAhOlYnLF6yyTBVZV7iWKCIfkwWvhxsXZmhZ9U3SrzzC2HOXitDLovH656LZGZHeWJWiXkCXFDVdIPpr1kXch3PXWQVs=

after_success: 
  - chmod +x ./resources/update-gh-pages.sh
  - ./resources/update-gh-pages.sh
